### ISSUE TITLE
Refname for remote repositories is not validated

### ISSUE THREAD

**Issue by stefreschke** [hpi-swa/Squot#248] opened 2019-11-03 13:28 UTC
Refname for git remote repositorys is not validated when adding a remote repo. In my case I gave it a refname containing serveral blanks.

**Comment by j4yk** [comment] 2020-09-06 20:16
@stefreschke Can you still reproduce this with the latest version? Please include the steps to reproduce. When I set the upstream branch to something with spaces in it, I get a debugger because of the failed name verification.

**Comment by j4yk** [comment] 2020-09-20 20:12
Ah, you can set a remote name with spaces, but since the remote name will be part of the ref names of remote-tracking branches, this is not allowed.

**Closed** 2020-09-21 23:45 UTC
Labels: FileSystem-Git, Squit, bug
