### ISSUE TITLE
No changes tracked during commit in Squeak 5.1

### ISSUE THREAD

**Issue by Jeilef** [hpi-swa/Squot#162] opened 2018-04-03 17:12 UTC
What I did:
1. Created new Package, Class and Method
2. Clicked "Started tracking packages" and selected my package
3. Added my remote
4. clicked commit and then I got this as my changes
![image](https://user-images.githubusercontent.com/18723935/38264323-e98f75a0-3772-11e8-9333-f9a39330a43b.png)

**Comment by j4yk** [comment] 2018-04-03 18:09
The naming conventions for Cypress packages bite again. When the package has been added, probably no subfolder in the Git working directory was selected. @Jeilef can you confirm this? Thus, the package artifact's `path` became the empty string. When the artifact is serialized into the Git tree, the path is changed to conform to the Cypress naming convention of `Firsttest.package`. When you look at the tree with Git's tools or try to load your package in a fresh project/image, you will find everything got written out correctly, wasn't it? But the path in the image store is still the incorrect one.

![image](https://user-images.githubusercontent.com/151175/38267096-be17df86-377a-11e8-9e21-e017d9ceb524.png)

Thus, the name "auto-correction" (`#squotRewritePath:with:`) must be invoked already when something is added to the store, not only when it is first serialized.

**Comment by Jeilef** [comment] 2018-04-03 18:40
Correct. I selected the root folder (the one where the .git Folder can be found in).

But there is nothing commited even if I click on commit after getting the empty diff (if you meant something else with "got written out correctly" please elaborate). Hence, I cant load anything in another Image

**Comment by j4yk** [comment] 2018-04-03 20:30
Well, that's odd. I have tried to reproduce your steps:
1. ![image](https://user-images.githubusercontent.com/151175/38273672-db89054c-378c-11e8-86fb-490fced9be25.png)
2. ![image](https://user-images.githubusercontent.com/151175/38273724-ffc15eb4-378c-11e8-89c8-441e12fc20f0.png)
3. ![image](https://user-images.githubusercontent.com/151175/38273751-0f5a241e-378d-11e8-87ea-e4fb64e649ea.png)
(ignore the typo... and do not think of pink elephants)
4. ![image](https://user-images.githubusercontent.com/151175/38273832-49f8fb18-378d-11e8-9eda-d4ca208756c4.png)

I get an additional error in `#cacheNewMonticelloVersion:Message:`, did you also observe that?
5. ![image](https://user-images.githubusercontent.com/151175/38273943-8d8d2750-378d-11e8-8d34-3dc9ccad3645.png)
I resume from this one by choosing 'return entered value' from that method (does not matter which value is returned there), and then 'proceed'.

6. ![image](https://user-images.githubusercontent.com/151175/38274038-d77b473e-378d-11e8-9755-6483df35ac81.png)

And when I look at the commit with TortoiseGit, for example, all the files are there:
7. ![image](https://user-images.githubusercontent.com/151175/38274080-f4a8d6f0-378d-11e8-87c1-f4e797b40b42.png)

From which step on do things differ for you? The image in which I took these screenshots is clean except for the breakpoints I put in to debug this issue.

**Comment by j4yk** [comment] 2018-04-03 21:32
9f72757

**Comment by tom95** [comment] 2018-04-04 09:30
On trunk, I run into a similar issue (hope this is related, so I'll just dump my picture story here...)

![screenshot from 2018-04-04 11 24 16](https://user-images.githubusercontent.com/4313751/38299802-7817a242-37fb-11e8-998b-7eef078f4ef5.png)
![screenshot from 2018-04-04 11 25 18](https://user-images.githubusercontent.com/4313751/38299812-7bc1474a-37fb-11e8-8cbe-3c4b4e5d7c2e.png)
![screenshot from 2018-04-04 11 25 40](https://user-images.githubusercontent.com/4313751/38299816-7e936cdc-37fb-11e8-9d22-7cfaf281a738.png)
![screenshot from 2018-04-04 11 26 17](https://user-images.githubusercontent.com/4313751/38299823-822a9b7c-37fb-11e8-8318-ca8eab335db2.png)
![screenshot from 2018-04-04 11 28 38](https://user-images.githubusercontent.com/4313751/38299827-852cc7b4-37fb-11e8-8edd-199ee7618f80.png)

**Comment by j4yk** [comment] 2018-04-04 10:15
@Jeilef: Do you get the same error as Tom?

+@tom95: I will only get to work on this in the evenings. You could try to solve it yourselves, if you have time: when the path of the package is rectified during serialization to Cypress files, a SquotPathChanged notification is signalled (see latest commits on branch 'squeak5.1'). This is apparently not applied to the diff/addition of the package yet. A good place to start looking where to do that is in `SquotWorkingCopy>>#saveNewVersionFromPatch:interactively:` (as I am typing this on my phone, the actual names might differ somewhat). If you do have the time, I would welcome a pull request.

**Comment by tom95** [comment] 2018-04-04 12:07
I'm away from my keyboard for the rest of the day unfortunately, but could start an attempt tomorrow. Just so I'm clear, am I supposed to be loading the squeak5.1 branch? In particular I am currently on a trunk image, but github tells me squeak5.1 has around 50 more commits than master.

**Comment by j4yk** [comment] 2018-04-04 12:14
Either 'squeak5.1' or 'develop'. I still have to cherry-pick yesterday's commits to 'develop'.

**Comment by Jeilef** [comment] 2018-04-04 17:55
@j4yk You reproduced my error exactly. I just didnt proceed after the Debugger can up. 

Like Tom I can only work in the evenings too

**Comment by j4yk** [comment] 2018-04-04 19:43
Ok, in this case I assume that the bug Tom described is already resolved on the develop branches (as of yet, squeak5.1 is one too).

**Comment by j4yk** [comment] 2018-04-04 21:15
@Jeilef @tom95 Please try again with the latest versions of the respective branches.

**Comment by tom95** [comment] 2018-04-05 11:36
@j4yk on my end (on trunk) it works flawlessly now, many thanks!

I realized now that it is possible that files were written before, since I had forgotten that the working copy is never updated. Nevertheless, the issue with the package being removed right after being added is gone and things seem to be working thus far :)

**Comment by Jeilef** [comment] 2018-04-05 16:56
When commit I dont get any error but still it doesnt Show any changes. I reinstalled Squot from the squeak5.1 branch
1. created new Project
2. started tracking new packages
![image](https://user-images.githubusercontent.com/18723935/38379844-4549ecc8-3902-11e8-82d8-af727c873390.png)
3. selected empty Folder
![image](https://user-images.githubusercontent.com/18723935/38379890-6bd0a300-3902-11e8-8fe8-0c94d20f4ce5.png)
4. get this warning
![image](https://user-images.githubusercontent.com/18723935/38379915-81cce5ba-3902-11e8-8b7b-ff095c1af677.png)
5. click commit and this window Shows
![image](https://user-images.githubusercontent.com/18723935/38379992-bb083ba4-3902-11e8-9a84-80cf25981fea.png)
6. committing gets me without error or warning to:
![image](https://user-images.githubusercontent.com/18723935/38380068-edb444d0-3902-11e8-9e7b-048ef8f4f585.png)
Here the package is listed.

**Comment by Jeilef** [comment] 2018-04-05 17:09
When adding an additional method (and previously commiting with the empty message) you are notified that the correct packages are changing. The correct changes still are not listed.
![image](https://user-images.githubusercontent.com/18723935/38380689-cde57cd0-3904-11e8-905f-303121ae0b5c.png)

**Comment by j4yk** [comment] 2018-04-05 20:36
> About to overwrite another object in the store.

Did you attempt to add multiple packages to the same project? Usually this appears when you choose the same folder/file for two consecutively added objects to the project.

The odd view in step 5 is currently to be expected and must yet be fixed, see #163. You can observe here that at this point, the package has not been "moved" yet according to the naming convention, so its path is still the empty string (path below the root directory), which subsequently becomes the label of the top node in that tree.

Your latest comment I do not understand. What was the situation before the commit? Apparently the package was removed again previously. Since you have a merge at the top of the history in the screenshot, might this be a consequence of #166 removing the package?

**Comment by j4yk** [comment] 2018-04-07 16:34
@Jeilef I have found and hopefully fixed another issue: When adding more than one package to the same folder, only the last of them was actually added (because each one would overwrite the previous, due to them having the same path, which is that of the selected folder). Now they get their corrected paths sooner, at the cost of creating a throw-away snapshot of the packages when they are added.

**Comment by j4yk** [comment] 2018-04-15 15:01
I assume that the remaining problems posted here are tracked in other tickets in this issue tracker (links are two comments above), so I am closing this issue. Please reopen if you think that the original problem or its solution still needs amending or open another issue if you experience other problems.

**Closed by j4yk** 2018-04-15 15:01 UTC
Labels: Squot, bug, mandatory
