### ISSUE TITLE
Cannot pull/merge after upgrade to v0.7.0

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swa/Squot#236] opened 2019-06-06 09:19 UTC
This is for a different repository than #235.
After creating a new commit, I wanted to pull upstream changes and merge them, so that I can push my new commit.
The problem is that `SquotPatch>>createNewBuilder` expects a `base` to be set on the `SquotPatch`:
![grafik](https://user-images.githubusercontent.com/2145092/59021478-2881d480-884c-11e9-8eb5-c97d8c663505.png)

That's because `SquotWorkingCopy>>mergeVersionInteractively:ifCanceled:`
 builds the patch using:
```smalltalk
SquotMergePatchBuilder new
		patchFrom: self currentSnapshot
		to: aVersion
		base: mergeBases anyOne.
```
`mergeBases anyOne` is a valid `SquitVersion`. However, `SquotMergePatchBuilder>>patchFrom:to:base:` calls `SquotMergePatchBuilder>>buildPatch` which creates a new `SquotPatch` but does **not** set its base.

**Comment by tom95** [comment] 2019-06-06 09:23
Applying random changes to the code, I found out that it appears to work again if we change `SquotMergeArtifcatBuilder>>patchFrom:to:base:`

to
```smalltalk
patchFrom: leftObjectContainer to: rightObjectContainer base: baseObjectContainer
	| base |
	self initialize.
	leftArtifacts := leftObjectContainer artifacts.
	rightArtifacts := rightObjectContainer artifacts.
	base := baseObjectContainer ifNil: [SquotSnapshot empty].
	baseArtifacts := base artifacts.
	fromBaseToIncoming := rightObjectContainer patchRelativeToBase: base.
	fromBaseToExisting := leftObjectContainer patchRelativeToBase: base.
	self mergePatches.
	leftLoadOrder := leftObjectContainer loadOrder.
	rightLoadOrder := rightObjectContainer loadOrder.
	baseLoadOrder := base loadOrder.
	self mergeLoadOrders.
	
	^ SquotPatch new
		initializeFrom: base to: rightObjectContainer withDiffs: (diffs reject: [:each | each hasChanges not]);
		loadOrderDiff: loadOrderPatch;
		yourself
```

that is, we use initializeFrom:to:withDiffs: instead of initializeWith: for the SquotPatch

**Comment by j4yk** [comment] 2019-06-06 10:30
Seems like your changes weren't so random after all. Sounds like I checked
that no code calls the old constructor, but I didn't check that no code
calls what the old constructor called... :-(

>

**Comment by j4yk** [comment] 2019-06-06 20:55
...or rather now I remember why I still have this "Senders of initializeWith:" MessageTrace window open in my image. D'oh!

**Comment by j4yk** [comment] 2019-06-06 21:41
Your patch idea is almost right. But the base of the SquotPatch is not the base of the merge in this case. The base/left/from-side of the patch is the left/existent side of the merge. The patched/right/to-side of the patch is the result of the merge.

You could try the attached changeset, but so far I did not even try it myself. Also the existing test cases don't seem to cover the situation, even though there are tests for merges.

[Squot236.1.cs.txt](https://github.com/hpi-swa/Squot/files/3263590/Squot236.1.cs.txt)

**Comment by cmfcmf** [comment] 2019-06-07 12:48
> You could try the attached changeset, but so far I did not even try it myself. Also the existing test cases don't seem to cover the situation, even though there are tests for merges.
> 
> [Squot236.1.cs.txt](https://github.com/hpi-swa/Squot/files/3263615/Squot236.1.cs.txt)

Thanks! This appears to be working 👍

**Comment by tom95** [comment] 2019-06-08 05:45
I actually ran into a problem with it while pulling and causing a merge:

![Screenshot from 2019-06-08 07-44-07](https://user-images.githubusercontent.com/4313751/59142625-52a8d300-89c1-11e9-8b6a-96eb9b1fbe2e.png)

Hope I loaded everything correctly...

**Comment by j4yk** [comment] 2019-06-08 17:03
Saw it during the tests. Unresolved conflicts are skipped in updatePatchedArtifacts now.

I pushed the fix to master, can you upgrade again and tell me if the problem is resolved?

**Comment by j4yk** [comment] 2019-07-13 18:34
Well, I assume it's resolved until I'm told otherwise.

**Closed by j4yk** 2019-07-13 18:34 UTC
Labels: Squot, bug
